name: Build

on:
  push:
    paths-ignore:
      - '*.md'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3  # Optional: This action can handle SDK setup more reliably
        with:
          sdk-version: '35'  # Align with build-tools

      - name: Build
        run: |
          export ANDROID_SDK_ROOT=/usr/local/lib/android/sdk  # Set explicitly if not from setup-android
          export PATH=$PATH:$ANDROID_SDK_ROOT/build-tools/35.0.0:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin
          
          yes | sdkmanager --licenses
          sdkmanager --verbose --install "platforms;android-29" "build-tools;35.0.0"
          
          APK_NAME="framework-res__auto_generated_rro"
          
          aapt package -v -M AndroidManifest.xml -S res --min-sdk-version 29 --target-sdk-version 29 -I $ANDROID_SDK_ROOT/platforms/android-29/android.jar -F ${APK_NAME}-unaligned.apk
                   
          zipalign -v 4 ${APK_NAME}-unaligned.apk ${APK_NAME}.apk
          apksigner sign -v --v1-signing-enabled false --key testdata/testkey.pk8 --cert testdata/testkey.x509.pem ${APK_NAME}.apk
          rm -f -v ${APK_NAME}-unaligned.apk ${APK_NAME}.apk.idsig

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: ta2cm8-overlay-customized
          path: framework-res__auto_generated_rro.apk
